name: CMake + Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # 1. Check out the code
      - uses: actions/checkout@v3

      # 2. Install & set up Python (match your CMake find_package version)
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install pytest (and any other Python deps)
      - name: Install Python test dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest

      # 4. Configure your CMake project
      - name: Configure
        run: cmake -S . -B build_win -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=${{ env.pythonLocation }}/python

      # 5. Build
      - name: Build
        run: cmake --build build_win --config Release      # 6. Debug: Check if the Python module was built correctly
      - name: Debug - List build output
        run: |
          echo "Contents of build_win/src/Release:"
          dir build_win\src\Release
          echo "Python version:"
          python --version
          echo "Python executable location:"
          where python
          echo "Checking Python module dependencies:"
          python -c "import sys; print('Python path:', sys.path)"

      # 7. Debug: Test Python module loading manually
      - name: Debug - Test module loading
        working-directory: build_win
        run: |
          echo "Testing manual module import:"
          python -c "import sys; sys.path.insert(0, 'src/Release'); print('Attempting to import shm_py...'); import shm_py; print('Success! Module loaded:', shm_py)"

      # 8. Run CTest (including your python_add_test)
      - name: Test
        working-directory: build_win
        run: ctest --output-on-failure -C Release
